config/routes.rb
Ideahub::Application.routes.draw do

  
  scope '/feathers' do
    match 'page/:type/(:status)' => 'feathers#page', :as => :feather_page
    get 'pages' => 'feathers#index', :as => :feather_pages
    get 'preivew/:type/(:status)' => 'feathers#preivew', :as => 'feather_page_preview'
  end
  get 'page/:type' => 'feathers#published', :as => 'feather_published_page'


  # Omniauth
  match "/signin" => redirect("/auth/twitter")
  match "/signout" => "services#signout"
  
  match '/auth/:service/callback' => 'services#create' 
  match '/auth/failure' => 'services#failure'

  resources :ideas do
    get 'participate', :on => :member
    resources :schedules
  end
  
  # used for the demo application only
  resources :users, :only => [:index] do
  end
   
  root :to => 'welcome#index'
end

app/models/idea.rb
class Idea < ActiveRecord::Base
  belongs_to :user
  has_many :idea_users, :dependent => :destroy
  has_many :users, :through => :idea_users
  has_many :comments, :dependent => :destroy
  has_many :schedules, :dependent => :destroy
  has_many :idea_categories, :dependent => :destroy
  has_many :categories, :through => :idea_categories

  validates :user_id, :title, :original_desc, :presence => true

  attr_accessible :title, :original_desc, :user_id, :category_ids, :github, :description

  before_save :format_description

  delegate :name, to: :user, prefix: true

  def format_description
    self.description = RedCloth.new(original_desc, [:lite_mode]).to_html
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]
  before_filter :get_idea, :only => [:update, :edit, :show, :participate]

  def index
    @ideas = Idea.includes(:users).includes(:categories)
  end

  def new 
    @schedule = Idea.new.schedules.new
  end

  def create
    @idea = Idea.new(params[:idea])
    params[:cat] and params[:cat].each { |cat| @idea.categories << Category.find_or_create_by_name(cat) }

    @idea.user = current_user
    @idea.users = [current_user]
    if @idea.save
      User.tweet "@#{current_user.screen_name} just had an idea \"#{@idea.title}\". Help him! #{ideas_url}"
      flash[:notice] = 'Idea created successfully'
      redirect_to :action => :index
    else
      render :action => :new
    end
  end

  # param[:category_ids] will always be empty, so when we call update_attributes, they will be
  # reset. Hence I have intentionally updated categories in both cases to ensure that 
  # they get updated only once!
  def update
    if @idea.update_attributes(params[:idea])
      params[:cat].each { |cat| @idea.categories << Category.find_or_create_by_name(cat) }
      flash[:notice] = 'Idea updated'
      redirect_to :action => :index
    else
      params[:cat].each { |cat| @idea.categories << Category.find_or_create_by_name(cat) }
      render :action => :edit
    end
  end

  def participate
    if @participant = @idea.users.include?(current_user) 
      IdeaUser.by_idea_and_user(current_user.id, @idea.id).first.destroy
    else
      @idea.users << current_user
      User.tweet("@#{current_user.screen_name} is helping out with '#{@idea.title}' on #{Time.now.strftime ('%d-%m-%Y %I:%M %p')}. Are you? #{idea_url(@idea)}")
    end
  end

  private
  def get_idea
    @idea = Idea.find_by_id(params[:id])
    @idea || invalid_url!
  end
end

app/helpers/ideas_helper.rb
module IdeasHelper

  def source_url(url)
    url =~ /^http/ ? url : "http://github.com/" 
  end

  def display_categories(idea)
    idea.categories.collect(&:name).join(', ').html_safe
  end

  def participate_button(idea)
    if user_signed_in?
      participant =  idea.users.include?(current_user) ? 'Leave' : 'Participate'
      link_to participant, participate_idea_path(idea), :class => 'participate btn btn-info', :remote => true
    else
      link_to 'Participate', participate_idea_path(idea), :class => 'participate btn btn-info', onclick: "alert('You need to login to participate,you will be redirected to twitter authentication');window.location='/auth/twitter'; return false;"
    end
  end

  def display_participants(idea)
    idea.users.collect{ |u|
      img_tag = image_tag("https://api.twitter.com/1/users/profile_image?screen_name=#{u.screen_name}&size=mini")
      link_to(img_tag, "http://twitter.com/#{u.screen_name}", :target => :_blank)
    }.join.html_safe
  end
end

app/views/ideas/_form.html.haml
.row.well
  = simple_form_for @idea ||= Idea.new, :html => { :class => 'span6 form-horizontal' }, :defaults => { :input_html => { :class => 'input-xlarge span8' } } do |f|
    %fieldset
      %legend Details
      = f.input :title
      = f.input :github, input_html: { value: source_url(@idea.github) }
      = render 'formatting_guide'
      = f.input :original_desc, :as => :text, :input_html => { :rows => 8 }, :label => "Description" 
      = f.input :category_ids, :input_html => { :class => 'typeahead', :data => { :provide => 'typeahead', :source => Category.all.collect(&:name).to_s }, :value => '', :autocomplete => 'off' }, :label => "Categories"
      #idea_categories
        %ul
          - @idea.categories.each do |cat|
            %li{:class => "token-input-token-facebook"}
              %p= cat.name
              %span.token-input-delete-token-facebook x
              %input{:name => 'cat[]', :type => 'hidden', :value => cat.name}
      .clear
      .form-actions.ideahub
        = f.button :submit, :class => 'btn btn-primary btn-large'
        %input{ :type => 'button', :value => 'Home', :class => 'btn btn-inverse btn-large', :onclick => "location.href='/'" }

app/views/ideas/_formatting_guide.html.haml
#formatting-guide.controls
  %a#toggle-guide{:href => "#"} How do I format idea description?
  #guide{:style => "display:none;"}
    %p
      You can enrich your description with bold and italic text, and by adding hyperlinks just by using a simple syntax, explained here:
    %table
      %tr
        %th
          %b If you type this…
        %th
          %b …you get this
      %tr
        %td _ideahub_
        %td
          %em ideahub
      %tr
        %td *ideahub*
        %td
          %strong ideahub
      %tr
        %td +ideahub+
        %td
          %u ideahub
      %tr
        %td "Ideahub":http://www.ideahub.com
        %td
          %a{:href => "http://www.ideahub.com"} Ideahub
:javascript
  $('#toggle-guide').click(function() { $('#guide').toggle('fast'); return false; });

app/views/ideas/_idea.html.haml
.grid{class: "idea-box grid-#{idea.id % 4} #{idea.categories.collect(&:name).join(' ')}", id: "idea-#{idea.id}"}
  %a{href: idea_path(idea)}
    %h2{class: "title"}
      = idea.title.truncate(17)
      %i{class: "#{'favorite' if idea.users.include?(current_user)}"}
  %h6.categoriesNames 
    = idea.categories.empty? ? 'No Categories' : idea.categories.limit(2).collect{|c| content_tag(:l, c.name, :style => 'cursor:pointer') }.join(', ').html_safe
  .description
    %span= raw idea.description.truncate(140)
    = link_to 'Overview', "#idea-detail-#{idea.id}", class: 'details btn btn-info', data: {toggle: 'modal'}
  .detail
    .floatLeft
      %i.icon-calendar>
      = idea.schedules.last.try(:scheduled_at).try(:idea_date) or "soon"
      |
    .floatLeft
      %i.icon-user>
      %span{:id => "idea_count_#{idea.id}"} #{idea.users.count}
    .floatRight
      = tweet_button :via => "punerb",:count=> "none", :url => idea_url(idea), :text => "This is an interesting idea! Help out "

  .modal{style: "display:none", id: "idea-detail-#{idea.id}"}
    .modal-header
      %button{class: "close", data: {:dismiss => "modal"}} x
      %h3= idea.title
    .modal-body
      %h5
        Categories:
      %h6
        = idea.categories.collect(&:name).join(', ')
      %h5
        Github URL: 
        = link_to idea.github, idea.github, target: '_blank'
      %h5.marTop10
        Idea By:
      %p
        =  idea.user_name
      %h5.marTop10
        Description
      %p= raw idea.description
    .modal-footer
      = participate_button(idea)
      - if idea.user == current_user
        =link_to "Edit", edit_idea_path(idea), class: 'btn'

app/views/ideas/edit.html.haml
= render 'form'

app/views/ideas/index.html.haml
.container.idea-index
  = render @ideas, participate: true

app/views/ideas/new.html.haml
= render 'form'

app/views/ideas/participate.js.haml
$('#idea_count_#{@idea.id}').text("#{@idea.users.count}")
- if @participant 
  $('#idea-#{@idea.id} a.participate.btn').text('Participate')
  $('#idea-#{@idea.id} a h2 i').removeClass('favorite')
  $('.participate.btn.btn-info').text('Participate')
- else
  $('#idea-#{@idea.id} a.participate.btn').text('Leave')
  $('.row .participate.btn.btn-info').text('Leave')
  $('#idea-#{@idea.id} a h2 i').addClass('favorite')

app/views/ideas/show.html.haml
- content_for :title do
  = @idea.title

= javascript_include_tag 'http://zor.livefyre.com/wjs/v1.0/javascripts/livefyre_init.js'

.well.grid
  .row
    %h2= @idea.title
    %h6= display_categories(@idea)
    %h5= link_to @idea.github, @idea.github, target: '_blank'

  %br
  .row
    = raw(@idea.description)
  %br
  .row
    = participate_button(@idea) 

  .row.participants
    %h5 Participants
    = display_participants(@idea)
  %br

  .row
    %h6
      Scheduled #{ @idea.schedules.last.try(:scheduled_at).try(:idea_date) or "soon" }

  .row
    :javascript
      var fyre = LF({site_id: 305993});