config/routes.rb
Ideahub::Application.routes.draw do

  
  scope '/feathers' do
    match 'page/:type/(:status)' => 'feathers#page', :as => :feather_page
    get 'pages' => 'feathers#index', :as => :feather_pages
    get 'preivew/:type/(:status)' => 'feathers#preivew', :as => 'feather_page_preview'
  end
  get 'page/:type' => 'feathers#published', :as => 'feather_published_page'


  # Omniauth
  match "/signin" => redirect("/auth/twitter")
  match "/signout" => "services#signout"
  
  match '/auth/:service/callback' => 'services#create' 
  match '/auth/failure' => 'services#failure'

  resources :ideas do
    get 'participate', :on => :member
    resources :schedules
  end
  
  # used for the demo application only
  resources :users, :only => [:index] do
  end
   
  root :to => 'welcome#index'
end

app/controllers/feathers_controller.rb
class FeathersController < ApplicationController

  if FeatherCms::Config.authentication.kind_of?(Hash)
    http_basic_authenticate_with FeatherCms::Config.authentication.merge(except: :published)
  else
    before_filter FeatherCms::Config.authentication.to_sym, except: :published
  end

  before_filter :find_page, only: [:page, :preivew]

  layout 'feather_layout', except: [:preivew, :published]

  def index
    @pages = FeatherPage.all
  end

  def page
    if request.put? or request.post?
      @feather_page.attributes = params[:feather_page]
      @feather_page.name = params[:type]
      @feather_page.save
    end
    render action:  @feather_page.name
  end

  def preivew
    render inline: @feather_page.content, type: 'html',  layout: @feather_page.layout
  end

  def published
    @feather_page = FeatherPage.where(name: params[:type], status: 'published').first 
    render inline: @feather_page.content, type: 'html',  layout: @feather_page.layout
  end

  def find_page
    status = params[:feather_page] ? params[:feather_page][:status] : (params[:status] || 'draft')
    @feather_page = FeatherPage.where(name: params[:type], status: status)
    @feather_page = @feather_page.first || @feather_page.new
  end
end

app/helpers/feathers_helper.rb
module FeathersHelper
  def feather_cms_include_tag
    javascript_include_tag('codemirror', 'modes/htmlmixed', 'modes/javascript',
                           'modes/xml', 'modes/css', 'feather_cms') + 
                           stylesheet_link_tag('codemirror')
  end

  def feather_cms_template(object_name, method, options = {})
    options[:class] = "#{options[:class]} codemirror_feather_cms"
    text_area(object_name, method, options = {})
  end

  def feather_cms_template_tag(name, content = nil, options = {})
    options[:class] = "#{options[:class]} codemirror_feather_cms"
    text_area_tag(name, content = nil, options = {})
  end

end

app/views/feathers/about_us.html.erb
<header>
<% status = params[:status] || @feather_page.status %> 
<div class="subnav">
  <ul class="nav nav-pills">
    <li class='<%= status == 'published' ? 'active ' : ''  %>'>
      <%= link_to 'Published Page', feather_page_path('about_us',:published) %> 
    </li>
    <li class='<%= status == 'draft' ? 'active ' : ''  %>'>
      <%= link_to 'Draft Page', feather_page_path('about_us', :draft) %>
    </li>
    <li>
    <%= link_to 'Preview', feather_page_preview_path('about_us', status), target: '_blank' unless @feather_page.new_record? %>
    </li>
  </ul>
</div>
<hr>
</header>
<div class="row">
  <div class="span12">
    <%= form_for(@feather_page, :url => feather_page_path('about_us')) do |f| %>
      <div class="control-group">
        <label class="control-label" for="status">Status</label>
        <div class="controls">
          <%= f.select :status, [:draft, :published]  %> 
        </div>
        <label class="control-label" for="layout">Layout</label>
        <div class="controls">
          <%= f.select :layout, FeatherCms::Config.layouts  %>
        </div>
      </div>
      <div class="control-group">
        <label class="control-label" for="textarea">Content</label>
        <div class="controls">
          <%= f.text_area :content, :class => 'codemirror_feather_cms input-xlarge span12', :row => "20" %>
        </div>
      </div>
      <%= f.submit "Save", :class => 'btn btn-primary btn-large' %>
    <% end %>
  </div>
</div>

app/views/feathers/credits.html.erb
<header>
<% status = params[:status] || @feather_page.status %> 
<div class="subnav">
  <ul class="nav nav-pills">
    <li class='<%= status == 'published' ? 'active ' : ''  %>'>
      <%= link_to 'Published Page', feather_page_path('credits',:published) %> 
    </li>
    <li class='<%= status == 'draft' ? 'active ' : ''  %>'>
      <%= link_to 'Draft Page', feather_page_path('credits', :draft) %>
    </li>
    <li>
    <%= link_to 'Preview', feather_page_preview_path('credits', status), target: '_blank' unless @feather_page.new_record? %>
    </li>
  </ul>
</div>
<hr>
</header>
<div class="row">
  <div class="span12">
    <%= form_for(@feather_page, :url => feather_page_path('credits')) do |f| %>
      <div class="control-group">
        <label class="control-label" for="status">Status</label>
        <div class="controls">
          <%= f.select :status, [:draft, :published]  %> 
        </div>
        <label class="control-label" for="layout">Layout</label>
        <div class="controls">
          <%= f.select :layout, FeatherCms::Config.layouts  %>
        </div>
      </div>
      <div class="control-group">
        <label class="control-label" for="textarea">Content</label>
        <div class="controls">
          <%= f.text_area :content, :class => 'codemirror_feather_cms input-xlarge span12', :row => "20" %>
        </div>
      </div>
      <%= f.submit "Save", :class => 'btn btn-primary btn-large' %>
    <% end %>
  </div>
</div>

app/views/feathers/index.html.erb
<div class="row">
  <ol>
    <% @pages.each do |page| %>
      <li>
        <strong>
        <%= link_to "#{page.name.humanize}(#{page.status})", feather_page_path(page.name, page.status) %>
        </strong>
      </li>
    <% end %>
  </ol>
</div>

app/views/feathers/why.html.erb
<header>
<% status = params[:status] || @feather_page.status %> 
<div class="subnav">
  <ul class="nav nav-pills">
    <li class='<%= status == 'published' ? 'active ' : ''  %>'>
      <%= link_to 'Published Page', feather_page_path('why',:published) %> 
    </li>
    <li class='<%= status == 'draft' ? 'active ' : ''  %>'>
      <%= link_to 'Draft Page', feather_page_path('why', :draft) %>
    </li>
    <li>
    <%= link_to 'Preview', feather_page_preview_path('why', status), target: '_blank' unless @feather_page.new_record? %>
    </li>
  </ul>
</div>
<hr>
</header>
<div class="row">
  <div class="span12">
    <%= form_for(@feather_page, :url => feather_page_path('why')) do |f| %>
      <div class="control-group">
        <label class="control-label" for="status">Status</label>
        <div class="controls">
          <%= f.select :status, [:draft, :published]  %> 
        </div>
        <label class="control-label" for="layout">Layout</label>
        <div class="controls">
          <%= f.select :layout, FeatherCms::Config.layouts  %>
        </div>
      </div>
      <div class="control-group">
        <label class="control-label" for="textarea">Content</label>
        <div class="controls">
          <%= f.text_area :content, :class => 'codemirror_feather_cms input-xlarge span12', :row => "20" %>
        </div>
      </div>
      <%= f.submit "Save", :class => 'btn btn-primary btn-large' %>
    <% end %>
  </div>
</div>