config/routes.rb
Ideahub::Application.routes.draw do

  
  scope '/feathers' do
    match 'page/:type/(:status)' => 'feathers#page', :as => :feather_page
    get 'pages' => 'feathers#index', :as => :feather_pages
    get 'preivew/:type/(:status)' => 'feathers#preivew', :as => 'feather_page_preview'
  end
  get 'page/:type' => 'feathers#published', :as => 'feather_published_page'


  # Omniauth
  match "/signin" => redirect("/auth/twitter")
  match "/signout" => "services#signout"
  
  match '/auth/:service/callback' => 'services#create' 
  match '/auth/failure' => 'services#failure'

  resources :ideas do
    get 'participate', :on => :member
    resources :schedules
  end
  
  # used for the demo application only
  resources :users, :only => [:index] do
  end
   
  root :to => 'welcome#index'
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
  belongs_to :idea
  validates :idea_id, :scheduled_at, :location, :presence => true

  validate :schedule_date

  delegate :title, :to => :idea, :prefix => false, :allow_nil => true

  attr_accessible :idea_id, :scheduled_at, :location

  def can_delete?
    scheduled_at > DateTime.now
  end

  private

  def schedule_date
    self.errors[:scheduled_at] = 'Schedule it in the future silly!' if self.scheduled_at < DateTime.now
  end

end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_filter :is_admin?
  before_filter :get_idea
  before_filter :get_schedule, :only => [:edit, :update, :destroy]

  def index
    @schedules = @idea.schedules
  end

  def new
    @schedule = @idea.schedules.new
    @s_date = Date.today
  end

  def create
    @schedule = @idea.schedules.new(params[:schedule])
    if @schedule.save
      @schedule.idea.users.each do |p|
        User.tweet("@#{p.screen_name}, do come to #{@schedule.location}. We're hacking on '#{@schedule.idea.title}' on #{@schedule.scheduled_at.idea_date} at 5.30pm. #{idea_url(@schedule.idea)}")
      end
      redirect_to idea_schedules_url(@idea)
    else
      @s_date = Date.today
      render :action => 'new'
    end
  end

  def update
    @schedule.attributes = params[:schedule]
    if @schedule.save
      redirect_to idea_schedules_url(@idea)
    else
      render :action => 'edit'
    end
  end

  def destroy
    unless @schedule.scheduled_at > DateTime.now and @schedule.destroy
      redirect_to idea_schedules_url(@idea, @schedule)
    end
  end

  private

  def get_idea
    @idea = Idea.find_by_id(params[:idea_id])
  end
  
  def get_schedule
    @schedule = Schedule.find_by_id(params[:id])
    @s_date = @schedule.scheduled_at
    @schedule || invalid_url!
  end

end

app/views/schedules/_form.html.haml
.row.well
  = simple_form_for [@idea, @schedule], :html => { :class => 'span6 form-horizontal' }, :defaults => { :input_html => { :class => 'input-xlarge' } } do |f|
    %fieldset
      %legend Details
      = f.input :scheduled_at, as: :string, input_html: {:value => "#{@s_date.strftime('%d/%m/%Y')}", data: { "date-format" => "dd/mm/yyyy"} }
      = f.input :location
      .form-actions.ideahub
        = f.button :submit, :class => 'btn btn-primary btn-large'

:javascript
  $('#schedule_scheduled_at').datepicker();

app/views/schedules/_schedule.html.haml
%tr{:class => "schedule#{schedule.id}"}
  %td=link_to schedule.title, idea_url(schedule.idea)
  %td= schedule.scheduled_at.strftime('%d/%m/%Y')
  %td= schedule.location
  %td=link_to 'Edit', edit_idea_schedule_url(schedule.idea, schedule)
  %td
    =link_to 'Delete', idea_schedule_url(schedule.idea.id, schedule), :method => :delete, :remote => true if schedule.can_delete?

app/views/schedules/destroy.js.haml
$('.schedule#{@schedule.id}').remove()

app/views/schedules/edit.html.haml
=render 'form'

app/views/schedules/index.html.haml
.row.well
  %table.table.table-striped
    %thead
      %tr
        %th Idea
        %th Scheduled at
        %th Location
    %tbody
      =render :partial => :schedule, :collection => @schedules

app/views/schedules/new.html.haml
=render 'form'