config/routes.rb
Ideahub::Application.routes.draw do

  
  scope '/feathers' do
    match 'page/:type/(:status)' => 'feathers#page', :as => :feather_page
    get 'pages' => 'feathers#index', :as => :feather_pages
    get 'preivew/:type/(:status)' => 'feathers#preivew', :as => 'feather_page_preview'
  end
  get 'page/:type' => 'feathers#published', :as => 'feather_published_page'


  # Omniauth
  match "/signin" => redirect("/auth/twitter")
  match "/signout" => "services#signout"
  
  match '/auth/:service/callback' => 'services#create' 
  match '/auth/failure' => 'services#failure'

  resources :ideas do
    get 'participate', :on => :member
    resources :schedules
  end
  
  # used for the demo application only
  resources :users, :only => [:index] do
  end
   
  root :to => 'welcome#index'
end

app/views/layouts/_alert.html.haml
- if flash.present?
  .modal#alertModal
    .alert{:class => "alert-#{flash.keys.first}"}
      %b= flash[flash.keys.first] 
:javascript
  $('#alertModal').fadeToggle(6000)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= "Ideahub :: #{content_for?(:title) ? yield(:title) : get_idea_quote}"
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    = yield :head
  %body
    .navbar.navbar-fixed-top
      .container
        %a.brand{:href => '/'} IdeaHub
        .nav-collapse
          %ul.nav
          %ul.nav.pull-right
            - if user_signed_in?
              %li
                = link_to "Create", new_idea_path, :class => :'pull-right'
              %li
                = link_to "Browse", ideas_path, :class => :'pull-right'
            %li.dropdown
              %a.dropdown-toggle{ :href => '#', "data-toggle" => "dropdown"}
                About
                %b.caret
              %ul.dropdown-menu
                %li
                  = link_to "Why?", feather_published_page_path('why')
                %li
                  = link_to "Credits", feather_published_page_path('credits')
                %li
                  = link_to "About Us", feather_published_page_path('about_us')
            - if user_signed_in?
              %li
                = link_to "Sign out", signout_path, class: 'pull-right'
            - else
              %li
                = link_to '', signin_path, class: 'twitter-image pull-right', title: 'Sign in with Twitter'
    - if params[:controller] == 'ideas' && params[:action] == 'index'  
      .grid.clearfix#wrapper
        = render 'layouts/alert'
        = yield
    -else
      .container
        = render 'layouts/alert'
        = yield
      

app/views/layouts/feather_layout.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Feather CMS</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <%= stylesheet_link_tag 'application' %>
    <%= javascript_include_tag 'application' %>
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
    </style>

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

  </head>

  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to 'Feather CMS', feather_pages_path, :class => 'brand' %>
          <div class="nav-collapse">
            <ul class="nav">
              <li class="<%= params[:type] == 'about_us' ? 'active' : '' %>">
                <%= link_to 'About us' , feather_page_path('about_us') %> 
              </li>
              <li class="<%= params[:type] == 'why' ? 'active' : '' %>">
                <%= link_to 'Why' , feather_page_path('why') %> 
              </li>
              <li class="<%= params[:type] == 'credits' ? 'active' : '' %>">
                <%= link_to 'Credits' , feather_page_path('credits') %> 
              </li>
  
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <%= yield %>
    </div> 

  </body>
</html>